# Generated by Django 3.1.4 on 2021-01-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CIN',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
