# Generated by Django 3.1.4 on 2021-03-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
